### ISSUE TITLE
Support for Mac

### ISSUE THREAD

**Issue by thomasklingbeil** [Pecacheu/dualshock#2]
Thanks for your great work!
I tried to use version 3.1.2 on a Mac, but unfortunately node-gyp cannot build the modules due to the missing `windows.h`. After removing the sbc references, `npm install` is able to build the module (I am aware that it might crash at some point, where sbc is needed - audio, correct?).

I am able to run a simple example now, but unfortunately, still the rumble/LED feature for the DS4 does not work via Bluetooth. Is this related to sbc as well or is there another issue? Using the USB connection it works as intended.

```
ds = require('dualshock')
devices = ds.getDevices("ds4");
gamepad = ds.open(devices[0])
gamepad.rumble(255, 255, 5, 5);
gamepad.setLed(255,0,0);
```

**Comment by thomasklingbeil** [comment]
@Pecacheu I'm not sure if you receive notifications for new issues. Please let me know, if there is any way I can support.

**Comment by Pecacheu** [comment]
Sorry I never see these things... Github is a bit sparratic on notifying me, IDK why.

Anyway, the SBC is needed for audio and on some controllers rumble / LED. They seem to behave slightly differently so it depends on the revision I think. But yeah, they're usually better behaved with the SBC data.

But I remember it working on my Mac, I don't know why the SBC lib wont compile. Maybe I was using a different one at the time.

**Comment by Pecacheu** [comment]
Oh, it's probably because of **HidD_Set_Output_Report**. The modified version of node-hid I'm using has a second argument to `hid.write`, which uses **HidD_Set_Output_Report** to write the Bluetooth data instead of the normal **WriteFile** approach. From my understanding, it uses a special message type, which the DS4 is looking for.

The MacOS HID library probably has a similar function, but I don't know what that is. The node-hid fork I used only implemented the change on the windows version.

**Comment by Nivekvb** [comment]
Any progress on this? Would be appreciated, allot!  👍 I'm stuck at 3.1.1

**Comment by audionerd** [comment]
[`main.cc` requires `Windows.h`](https://github.com/Pecacheu/dualshock/blob/22888b6053b2aa1768309a52a9d4170ab68d09d4/main.cc#L2). It would need to be modified to handle other platforms.

Currently, building via `node-gyp build` on macOS fails with errors, e.g.:

```cpp
../main.cc:18:26: error: unknown type name 'DWORD'
char *eCode(string name, DWORD hr) {
                         ^
../main.cc:19:2: error: unknown type name 'LPSTR'
        LPSTR buf = nullptr; size_t size = FormatMessageA(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM...
        ^
...
```

**Comment by danimesq** [comment]
Its not a problem on GitHub's side; simply, @Pecacheu have abandonned this project.

This package still have a lot of potential, such as getting support to the DualSense gamepad.

**Comment by Pecacheu** [comment]
@danimesq If I pick up a DualSense controller in the future I would love to add support for them and the new features I've heard cool stuff about, but I don't currently have one to test with, nor a PS5 which are still being scalped to hell and back at the moment.

That said I haven't abandoned the project I just didn't have any issues with it for my own purposes so I've been lazy, lol. If someone would open a pull request with fixes that would be excellent, otherwise I can look into this next time I have some time.

My modified node-hid lib is probably out of date by now anyhow.
