### ISSUE TITLE
HID write requires only one argument

### ISSUE THREAD

**Issue by dkaraush** [Pecacheu/dualshock#4]
How to reproduce:
```
$ node
> ds = require('dualshock');
> g = ds.open(ds.getDevices("ds4")[0]);
> g.rumble(255,255);
```
How to fix:
In `ds4.js` just remove second argument in 99 line:
```
- dev.write(msg, true);
+ dev.write(msg);
```
Why?
I probably think it's because of a new version of `node-hid`. You have tested 5 months ago, when `node-hid` didn't check for count of arguments.

**Comment by Pecacheu** [comment]
You're using the wrong version of `node-hid`. This library **ONLY** works with [this fork](/Pecacheu/node-hid) of node-hid (using [this fork](https://github.com/jarveson/hidapi) of HID API), which it should come pre-bundled with.

This is because the HID API team refuses to listen to our suggestions, and it's missing a number of important features. _I swear, every time I need to use node-hid, I have to find a new fork of HID API with the feature I need implemented._

**Comment by Pecacheu** [comment]
Alright, I think I've managed to make npm install the correct fork on it's own. Apperently the newer versions of npm think they are smarter than you are and they overwrite the `node_modules` folder contents. So, rather than including it pre-built, like I was doing before, I've put it back in the json, but this time referencing the fork rather than the normal branch.
